var PS={};
(function(a){a.arrayMap=function(a){return function(b){for(var e=b.length,d=Array(e),g=0;g<e;g++)d[g]=a(b[g]);return d}};a.arrayBind=function(a){return function(b){for(var e=[],d=0,g=a.length;d<g;d++)Array.prototype.push.apply(e,b(a[d]));return e}};a.concatString=function(a){return function(b){return a+b}};a.concatArray=function(a){return function(b){return a.concat(b)}};a.refEq=function(a){return function(b){return a===b}};a.unsafeCompareImpl=function(a){return function(b){return function(e){return function(d){return function(g){return d<g?
a:d>g?e:b}}}}};a.topInt=2147483647;a.bottomInt=-2147483648;a.showIntImpl=function(a){return a.toString()};a.showNumberImpl=function(a){return a===(a|0)?a+".0":a.toString()};a.showCharImpl=function(a){var b=a.charCodeAt(0);if(32>b||127===b){switch(a){case "a":return"'\\a'";case "\b":return"'\\b'";case "\f":return"'\\f'";case "\n":return"'\\n'";case "\r":return"'\\r'";case "\t":return"'\\t'";case "\v":return"'\\v'"}return"'\\"+b.toString(10)+"'"}return"'"===a||"\\"===a?"'\\"+a+"'":"'"+a+"'"};a.showStringImpl=
function(a){var b=a.length;return'"'+a.replace(/[\0-\x1F\x7F"\\]/g,function(e,d){switch(e){case '"':case "\\":return"\\"+e;case "a":return"\\a";case "\b":return"\\b";case "\f":return"\\f";case "\n":return"\\n";case "\r":return"\\r";case "\t":return"\\t";case "\v":return"\\v"}var g=d+1,g=g<b&&"0"<=a[g]&&"9">=a[g]?"\\&":"";return"\\"+e.charCodeAt(0).toString(10)+g})+'"'}})(PS.Prelude=PS.Prelude||{});
(function(a){var c=PS.Prelude,b=function(){function a(){}a.value=new a;return a}(),e=function(){function a(){}a.value=new a;return a}(),d=function(){function a(){}a.value=new a;return a}(),g=function(a){this.compose=a},h=function(a,c){this["__superclass_Prelude.Semigroupoid_0"]=a;this.id=c},k=function(a){this.map=a},p=function(a,c){this["__superclass_Prelude.Functor_0"]=a;this.apply=c},l=function(a,c){this["__superclass_Prelude.Apply_0"]=a;this.pure=c},t=function(a,c){this["__superclass_Prelude.Apply_0"]=
a;this.bind=c},f=function(a,c){this["__superclass_Prelude.Applicative_0"]=a;this["__superclass_Prelude.Bind_1"]=c},r=function(a){this.append=a},w=function(a){this.eq=a},x=function(a,c){this["__superclass_Prelude.Eq_0"]=a;this.compare=c},y=function(a,c){this.bottom=a;this.top=c},q=function(a){this.show=a},v=c.unsafeCompareImpl(b.value)(d.value)(e.value),B=new q(c.showStringImpl),u=new q(c.showNumberImpl),J=new q(c.showIntImpl),n=new q(c.showCharImpl),K=new q(function(a){if(a)return"true";if(!a)return"false";
throw Error("Failed pattern match at Prelude line 841, column 1 - line 845, column 1: "+[a.constructor.name]);}),I=new g(function(a){return function(c){return function(b){return a(c(b))}}}),m=new r(c.concatString),D=new r(c.concatArray),z=function(a){return a.pure},A=new k(c.arrayMap),H=new w(c.refEq),C=new x(function(){return H},v),M=new k(I.compose),E=new h(function(){return I},function(a){return a}),F=new y(c.bottomInt,c.topInt),G=function(a){return a.bind},Q=function(a){return a.apply},R=function(a){return function(c){return function(b){return G(a["__superclass_Prelude.Bind_1"]())(c)(function(c){return G(a["__superclass_Prelude.Bind_1"]())(b)(function(b){return z(a["__superclass_Prelude.Applicative_0"]())(c(b))})})}}},
L=new f(function(){return S},function(){return T}),T=new t(function(){return P},c.arrayBind),P=new p(function(){return A},R(L)),S=new l(function(){return P},function(a){return[a]});a.LT=b;a.GT=e;a.EQ=d;a.Show=q;a.Bounded=y;a.Ord=x;a.Eq=w;a.Semigroup=r;a.Monad=f;a.Bind=t;a.Applicative=l;a.Apply=p;a.Functor=k;a.Category=h;a.Semigroupoid=g;a.show=function(a){return a.show};a.bottom=function(a){return a.bottom};a.top=function(a){return a.top};a.unsafeCompare=v;a["<="]=function(a){return function(c){return function(b){return(0,a.compare)(c)(b)instanceof
e?!1:!0}}};a["<"]=function(a){return function(c){return function(d){return(0,a.compare)(c)(d)instanceof b?!0:!1}}};a.compare=function(a){return a.compare};a["=="]=function(a){return a.eq};a.eq=function(a){return a.eq};a["++"]=function(a){return a.append};a["<>"]=function(a){return a.append};a.append=function(a){return a.append};a.ap=R;a["return"]=z;a.bind=G;a.liftA1=function(a){return function(c){return function(b){return Q(a["__superclass_Prelude.Apply_0"]())((0,a.pure)(c))(b)}}};a.pure=function(a){return a.pure};
a["<*>"]=Q;a.apply=function(a){return a.apply};a["<$>"]=function(a){return a.map};a.map=function(a){return a.map};a.id=function(a){return a.id};a.compose=function(a){return a.compose};a["const"]=function(a){return function(c){return a}};a.flip=function(a){return function(c){return function(b){return a(b)(c)}}};a.unit={};a.semigroupoidFn=I;a.categoryFn=E;a.functorFn=M;a.functorArray=A;a.applyArray=P;a.applicativeArray=S;a.bindArray=T;a.monadArray=L;a.semigroupString=m;a.semigroupArray=D;a.eqString=
H;a.ordString=C;a.boundedInt=F;a.showBoolean=K;a.showInt=J;a.showNumber=u;a.showChar=n;a.showString=B})(PS.Prelude=PS.Prelude||{});
(function(a){var c=PS.Prelude;a.lift2=function(a){return function(e){return function(d){return function(g){return c["<*>"](a)(c["<$>"](a["__superclass_Prelude.Functor_0"]())(e)(d))(g)}}}};a["*>"]=function(a){return function(e){return function(d){return c["<*>"](a)(c["<$>"](a["__superclass_Prelude.Functor_0"]())(c["const"](c.id(c.categoryFn)))(e))(d)}}}})(PS["Control.Apply"]=PS["Control.Apply"]||{});
(function(a){a.returnE=function(a){return function(){return a}};a.bindE=function(a){return function(b){return function(){return b(a())()}}}})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){var c=PS["Control.Monad.Eff"],b=PS.Prelude,e=new b.Monad(function(){return h},function(){return d}),d=new b.Bind(function(){return g},c.bindE),g=new b.Apply(function(){return k},b.ap(e)),h=new b.Applicative(function(){return g},c.returnE),k=new b.Functor(b.liftA1(h));a.functorEff=k;a.applyEff=g;a.applicativeEff=h;a.bindEff=d;a.monadEff=e})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){a.length=function(a){return a.length};a.cons=function(a){return function(b){return[a].concat(b)}};a.snoc=function(a){return function(b){var e=a.slice();e.push(b);return e}};a.concat=function(a){for(var b=[],e=0,d=a.length;e<d;e++)for(var g=a[e],h=0,k=g.length;h<k;h++)b.push(g[h]);return b};a.filter=function(a){return function(b){return b.filter(a)}};a.slice=function(a){return function(b){return function(e){return e.slice(a,b)}}}})(PS["Data.Array"]=PS["Data.Array"]||{});
(function(a){a.foldrArray=function(a){return function(b){return function(e){for(var d=b,g=e.length-1;0<=g;g--)d=a(e[g])(d);return d}}};a.foldlArray=function(a){return function(b){return function(e){for(var d=b,g=e.length,h=0;h<g;h++)d=a(d)(e[h]);return d}}}})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){var c=PS.Prelude,b=function(a,c){this["__superclass_Prelude.Semigroup_0"]=a;this.mempty=c},e=new b(function(){return c.semigroupString},"");a.Monoid=b;a.mempty=function(a){return a.mempty};a.monoidString=e})(PS["Data.Monoid"]=PS["Data.Monoid"]||{});
(function(a){var c=PS.Prelude,b=function(){function a(){}a.value=new a;return a}(),e=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),d=function(a){return function(c){return function(d){if(d instanceof b)return a;if(d instanceof e)return c(d.value0);throw Error("Failed pattern match at Data.Maybe line 26, column 1 - line 27, column 1: "+[a.constructor.name,c.constructor.name,d.constructor.name]);}}},g=d(!1)(c["const"](!0)),h=new c.Functor(function(a){return function(c){return c instanceof
e?new e(a(c.value0)):b.value}}),k=new c.Apply(function(){return h},function(a){return function(d){if(a instanceof e)return c["<$>"](h)(a.value0)(d);if(a instanceof b)return b.value;throw Error("Failed pattern match at Data.Maybe line 121, column 1 - line 145, column 1: "+[a.constructor.name,d.constructor.name]);}}),p=new c.Applicative(function(){return k},e.create);a.Nothing=b;a.Just=e;a.isJust=g;a.fromMaybe=function(a){return d(a)(c.id(c.categoryFn))};a.maybe=d;a.functorMaybe=h;a.applyMaybe=k;a.applicativeMaybe=
p})(PS["Data.Maybe"]=PS["Data.Maybe"]||{});
(function(a){var c=PS["Data.Foldable"],b=PS.Prelude,e=PS["Control.Apply"],d=PS["Data.Maybe"],g=PS["Data.Monoid"],h=function(a,c,b){this.foldMap=a;this.foldl=c;this.foldr=b},k=function(a){return function(c){return function(d){return(0,c.foldr)(function(c){return e["*>"](a["__superclass_Prelude.Apply_0"]())(d(c))})(b.pure(a)(b.unit))}}},p=new h(function(a){return function(c){return function(b){if(b instanceof d.Nothing)return g.mempty(a);if(b instanceof d.Just)return c(b.value0);throw Error("Failed pattern match at Data.Foldable line 103, column 1 - line 111, column 1: "+
[c.constructor.name,b.constructor.name]);}}},function(a){return function(c){return function(b){if(b instanceof d.Nothing)return c;if(b instanceof d.Just)return a(c)(b.value0);throw Error("Failed pattern match at Data.Foldable line 103, column 1 - line 111, column 1: "+[a.constructor.name,c.constructor.name,b.constructor.name]);}}},function(a){return function(c){return function(b){if(b instanceof d.Nothing)return c;if(b instanceof d.Just)return a(b.value0)(c);throw Error("Failed pattern match at Data.Foldable line 103, column 1 - line 111, column 1: "+
[a.constructor.name,c.constructor.name,b.constructor.name]);}}}),l=function(a){return function(c){return function(d){return function(e){return(0,a.foldr)(function(a){return function(e){return b["<>"](c["__superclass_Prelude.Semigroup_0"]())(d(a))(e)}})(g.mempty(c))(e)}}}},t=new h(function(a){return l(t)(a)},c.foldlArray,c.foldrArray);a.Foldable=h;a.intercalate=function(a){return function(c){return function(d){return function(e){return(0,a.foldl)(function(a){return function(e){return a.init?{init:!1,
acc:e}:{init:!1,acc:b["<>"](c["__superclass_Prelude.Semigroup_0"]())(a.acc)(b["<>"](c["__superclass_Prelude.Semigroup_0"]())(d)(e))}}})({init:!0,acc:g.mempty(c)})(e).acc}}}};a.for_=function(a){return function(c){return b.flip(k(a)(c))}};a.traverse_=k;a.fold=function(a){return function(c){return(0,a.foldMap)(c)(b.id(b.categoryFn))}};a.foldMapDefaultR=l;a.foldMap=function(a){return a.foldMap};a.foldl=function(a){return a.foldl};a.foldr=function(a){return a.foldr};a.foldableArray=t;a.foldableMaybe=p})(PS["Data.Foldable"]=
PS["Data.Foldable"]||{});
(function(a){a.traverseArrayImpl=function(){function a(c){this.fn=c}function b(a){return function(c){return new g(a,c)}}function e(a){for(var c=[];a!==d;)c.push(a.head),a=a.tail;return c}var d={},g=function(a,c){this.head=a;this.tail=c};return function(g){return function(k){return function(p){return function(l){var t=function(d,e,p){if(0===e)return d;var x=p[e-1];return new a(function(){var a=t,c;c=g(k(b)(l(x)))(d);return a(c,e-1,p)})};return function(b){for(b=t(p(d),b.length,b);b instanceof a;)b=
b.fn();return k(e)(b)}}}}}}()})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});
(function(a){var c=PS["Data.Traversable"],b=PS.Prelude,e=PS["Data.Foldable"],d=function(a,c,b,d){this["__superclass_Data.Foldable.Foldable_1"]=a;this["__superclass_Prelude.Functor_0"]=c;this.sequence=b;this.traverse=d},g=function(a){return function(c){return function(d){return(0,a.traverse)(c)(b.id(b.categoryFn))(d)}}},h=new d(function(){return e.foldableArray},function(){return b.functorArray},function(a){return g(h)(a)},function(a){return c.traverseArrayImpl(b.apply(a["__superclass_Prelude.Apply_0"]()))(b.map(a["__superclass_Prelude.Apply_0"]()["__superclass_Prelude.Functor_0"]()))(b.pure(a))});
a.Traversable=d;a.sequenceDefault=g;a.sequence=function(a){return a.sequence};a.traverse=function(a){return a.traverse};a.traversableArray=h})(PS["Data.Traversable"]=PS["Data.Traversable"]||{});(function(a){var c=function(){function a(c,b){this.value0=c;this.value1=b}a.create=function(c){return function(d){return new a(c,d)}};return a}();a.Tuple=c})(PS["Data.Tuple"]=PS["Data.Tuple"]||{});
(function(a){var c=PS["Data.Array"],b=PS.Prelude,e=PS["Data.Maybe"],d=function(a){return[a]},g=b.flip(b.bind(b.bindArray)),h=function(a){return g(function(c){return e.maybe([])(d)(a(c))})},b=h(b.id(b.categoryFn));a.catMaybes=b;a.mapMaybe=h;a.concatMap=g;a["null"]=function(a){return 0===c.length(a)};a.singleton=d;a.filter=c.filter;a.snoc=c.snoc;a.cons=c.cons;a.length=c.length})(PS["Data.Array"]=PS["Data.Array"]||{});
(function(a){a.unsafeIndex=function(a){return function(b){return a[b]}}})(PS["Data.Array.Unsafe"]=PS["Data.Array.Unsafe"]||{});(function(a){var c=PS["Data.Array.Unsafe"],b=PS["Data.Array"];a.last=function(a){return c.unsafeIndex(a)(b.length(a)-1)}})(PS["Data.Array.Unsafe"]=PS["Data.Array.Unsafe"]||{});(function(a){a.toCharCode=function(a){return a.charCodeAt(0)}})(PS["Data.Char"]=PS["Data.Char"]||{});(function(a){a.toCharCode=PS["Data.Char"].toCharCode})(PS["Data.Char"]=PS["Data.Char"]||{});
(function(a){var c=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),b=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}();a.Left=c;a.Right=b})(PS["Data.Either"]=PS["Data.Either"]||{});
(function(a){a.Enum=function(a,b,e,d,g,h){this["__superclass_Prelude.Bounded_0"]=a;this.cardinality=b;this.fromEnum=e;this.pred=d;this.succ=g;this.toEnum=h};a.defaultPred=function(a){return function(b){return function(e){return a(b(e)-1)}}};a.defaultSucc=function(a){return function(b){return function(e){return a(b(e)+1|0)}}};a.toEnum=function(a){return a.toEnum};a.succ=function(a){return a.succ};a.pred=function(a){return a.pred};a.fromEnum=function(a){return a.fromEnum};a.cardinality=function(a){return a.cardinality}})(PS["Data.Enum"]=
PS["Data.Enum"]||{});
(function(a){a._charAt=function(a){return function(b){return function(e){return function(d){return 0<=e&&e<d.length?a(d.charAt(e)):b}}}};a._charCodeAt=function(a){return function(b){return function(e){return function(d){return 0<=e&&e<d.length?a(d.charCodeAt(e)):b}}}};a._indexOf=function(a){return function(b){return function(e){return function(d){d=d.indexOf(e);return-1===d?b:a(d)}}}};a.length=function(a){return a.length};a.split=function(a){return function(b){return b.split(a)}};a.joinWith=function(a){return function(b){return b.join(a)}}})(PS["Data.String"]=
PS["Data.String"]||{});(function(a){var c=PS["Data.String"],b=PS["Data.Maybe"],e=c._indexOf(b.Just.create)(b.Nothing.value),d=c._charCodeAt(b.Just.create)(b.Nothing.value),g=c._charAt(b.Just.create)(b.Nothing.value);a.indexOf=e;a.contains=function(a){return function(c){return b.isJust(e(a)(c))}};a.charCodeAt=d;a.charAt=g;a.joinWith=c.joinWith;a.split=c.split;a.length=c.length})(PS["Data.String"]=PS["Data.String"]||{});
(function(a){var c=function(){function a(){}a.value=new a;return a}();a.Proxy=c})(PS["Type.Proxy"]=PS["Type.Proxy"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Either"],e=PS["Data.Maybe"],d=PS["Data.Tuple"],g=PS["Data.Traversable"],h=PS["Data.Array"],k=PS["Data.String"],p=PS["Type.Proxy"],l=function(){function a(c,b){this.value0=c;this.value1=b}a.create=function(c){return function(b){return new a(c,b)}};return a}(),t=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),f=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),r=function(){function a(c){this.value0=
c}a.create=function(c){return new a(c)};return a}(),w=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),x=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),y=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),q=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),v=function(){function a(c,b){this.value0=c;this.value1=b}a.create=function(c){return function(b){return new a(c,
b)}};return a}(),B=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),u=function(){function a(){}a.value=new a;return a}(),J=function(){function a(){}a.value=new a;return a}(),n=function(){function a(){}a.value=new a;return a}(),K=function(){function a(){}a.value=new a;return a}(),I=function(){function a(){}a.value=new a;return a}(),m=function(){function a(c){this.value0=c}a.create=function(c){return new a(c)};return a}(),D=function(a,c,b){this.fromSpine=a;this.toSignature=
c;this.toSpine=b},z=new D(function(a){return a instanceof x?new e.Just(a.value0):e.Nothing.value},function(a){return K.value},function(a){return new x(a)}),A=function(a){return function(b){if(b instanceof l){var d=function(a){return function(c){if(!a)return c;if(a)return"("+(c+")");throw Error("Failed pattern match at Data.Generic line 240, column 9 - line 241, column 9: "+[a.constructor.name,c.constructor.name]);}},e=h["null"](b.value1);if(e)return b.value0;if(!e)return d(10<a)(b.value0+(" "+k.joinWith(" ")(c.map(c.functorArray)(function(a){return A(11)(a(c.unit))})(b.value1))));
throw Error("Failed pattern match: "+[e.constructor.name]);}if(b instanceof t)return"{"+(k.joinWith(", ")(c.map(c.functorArray)(function(a){return a.recLabel+(": "+A(0)(a.recValue(c.unit)))})(b.value0))+"}");if(b instanceof r)return c.show(c.showBoolean)(b.value0);if(b instanceof w)return c.show(c.showInt)(b.value0);if(b instanceof f)return c.show(c.showNumber)(b.value0);if(b instanceof x)return c.show(c.showString)(b.value0);if(b instanceof y)return c.show(c.showChar)(b.value0);if(b instanceof q)return"["+
(k.joinWith(", ")(c.map(c.functorArray)(function(a){return A(0)(a(c.unit))})(b.value0))+"]");throw Error("Failed pattern match: "+[a.constructor.name,b.constructor.name]);}},H=new D(function(a){return a instanceof f?new e.Just(a.value0):e.Nothing.value},function(a){return u.value},function(a){return new f(a)}),C=new D(function(a){return a instanceof w?new e.Just(a.value0):e.Nothing.value},function(a){return n.value},function(a){return new w(a)}),M=new D(function(a){return a instanceof y?new e.Just(a.value0):
e.Nothing.value},function(a){return I.value},function(a){return new y(a)}),E=new D(function(a){return a instanceof r?new e.Just(a.value0):e.Nothing.value},function(a){return J.value},function(a){return new r(a)}),F=p.Proxy.value;a.SigProd=v;a.SigRecord=B;a.SigNumber=u;a.SigBoolean=J;a.SigInt=n;a.SigString=K;a.SigChar=I;a.SigArray=m;a.SProd=l;a.SRecord=t;a.SNumber=f;a.SBoolean=r;a.SInt=w;a.SString=x;a.SChar=y;a.SArray=q;a.Generic=D;a.gShow=function(a){return function(c){return A(0)((0,a.toSpine)(c))}};
a.fromSpine=function(a){return a.fromSpine};a.toSignature=function(a){return a.toSignature};a.toSpine=function(a){return a.toSpine};a.genericNumber=H;a.genericInt=C;a.genericString=z;a.genericChar=M;a.genericBool=E;a.genericArray=function(a){return new D(function(b){return b instanceof q?g.traverse(g.traversableArray)(e.applicativeMaybe)(function(b){return(0,a.fromSpine)(b(c.unit))})(b.value0):e.Nothing.value},function(c){return new m(function(c){return(0,a.toSignature)(F)})},function(b){return new q(c["<$>"](c.functorArray)(function(c){return function(b){return(0,a.toSpine)(c)}})(b))})};
a.genericTuple=function(a){return function(b){return new D(function(n){return n instanceof l&&"Data.Tuple.Tuple"===n.value0&&2===n.value1.length?c["<*>"](e.applyMaybe)(c["<$>"](e.functorMaybe)(d.Tuple.create)((0,a.fromSpine)(n.value1[0](c.unit))))((0,b.fromSpine)(n.value1[1](c.unit))):e.Nothing.value},function(c){return new v("Data.Tuple.Tuple",[{sigConstructor:"Data.Tuple.Tuple",sigValues:[function(c){return(0,a.toSignature)(F)},function(a){return(0,b.toSignature)(F)}]}])},function(c){return new l("Data.Tuple.Tuple",
[function(b){return(0,a.toSpine)(c.value0)},function(a){return(0,b.toSpine)(c.value1)}])})}};a.genericMaybe=function(a){return new D(function(b){return b instanceof l&&"Data.Maybe.Just"===b.value0&&1===b.value1.length?c["<$>"](e.functorMaybe)(e.Just.create)((0,a.fromSpine)(b.value1[0](c.unit))):b instanceof l&&"Data.Maybe.Nothing"===b.value0&&0===b.value1.length?c["return"](e.applicativeMaybe)(e.Nothing.value):e.Nothing.value},function(c){return new v("Data.Maybe.Maybe",[{sigConstructor:"Data.Maybe.Just",
sigValues:[function(c){return(0,a.toSignature)(F)}]},{sigConstructor:"Data.Maybe.Nothing",sigValues:[]}])},function(c){if(c instanceof e.Just)return new l("Data.Maybe.Just",[function(b){return(0,a.toSpine)(c.value0)}]);if(c instanceof e.Nothing)return new l("Data.Maybe.Nothing",[]);throw Error("Failed pattern match at Data.Generic line 197, column 1 - line 214, column 1: "+[c.constructor.name]);})};a.genericEither=function(a){return function(d){return new D(function(n){return n instanceof l&&"Data.Either.Left"===
n.value0&&1===n.value1.length?c["<$>"](e.functorMaybe)(b.Left.create)((0,a.fromSpine)(n.value1[0](c.unit))):n instanceof l&&"Data.Either.Right"===n.value0&&1===n.value1.length?c["<$>"](e.functorMaybe)(b.Right.create)((0,d.fromSpine)(n.value1[0](c.unit))):e.Nothing.value},function(c){return new v("Data.Either.Either",[{sigConstructor:"Data.Either.Left",sigValues:[function(c){return(0,a.toSignature)(F)}]},{sigConstructor:"Data.Either.Right",sigValues:[function(a){return(0,d.toSignature)(F)}]}])},function(c){if(c instanceof
b.Left)return new l("Data.Either.Left",[function(b){return(0,a.toSpine)(c.value0)}]);if(c instanceof b.Right)return new l("Data.Either.Right",[function(a){return(0,d.toSpine)(c.value0)}]);throw Error("Failed pattern match at Data.Generic line 214, column 1 - line 235, column 1: "+[c.constructor.name]);})}}})(PS["Data.Generic"]=PS["Data.Generic"]||{});
(function(a){a.fromStringImpl=function(a){return function(b){return function(e){e=parseFloat(e);return(e|0)===e?a(e):b}}}})(PS["Data.Int"]=PS["Data.Int"]||{});(function(a){var c=PS["Data.Maybe"],c=PS["Data.Int"].fromStringImpl(c.Just.create)(c.Nothing.value);a.even=function(a){return 0===(a&1)};a.fromString=c})(PS["Data.Int"]=PS["Data.Int"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Foldable"],e=PS["Data.Monoid"],d=function(){function a(){}a.value=new a;return a}(),g=function(){function a(c,b){this.value0=c;this.value1=b}a.create=function(c){return function(b){return new a(c,b)}};return a}(),h=g.create,k=new c.Semigroup(function(a){return function(b){if(a instanceof d)return b;if(a instanceof g)return new g(a.value0,c["<>"](k)(a.value1)(b));throw Error("Failed pattern match: "+[a.constructor.name,b.constructor.name]);}}),p=function(){return function(a){return function(c){var b=
a;a:for(;;){if(c instanceof d)return b;if(c instanceof g){b=new g(c.value0,b);c=c.value1;continue a}throw Error("Failed pattern match at Data.List line 368, column 1 - line 369, column 1: "+[b.constructor.name,c.constructor.name]);}}}(d.value)}(),l=new c.Functor(function(a){return function(c){return p(function(c){return function(b){var e=c,f=b;a:for(;;){if(e instanceof d)return f;if(e instanceof g){b=e.value1;f=new g(a(e.value0),f);e=b;continue a}throw Error("Failed pattern match at Data.List line 731, column 1 - line 738, column 1: "+
[e.constructor.name,f.constructor.name]);}}}(c)(d.value))}}),t=function(a){return b.foldr(a)(g.create)(d.value)},f=new b.Foldable(function(a){return function(d){return b.foldl(f)(function(b){return function(e){return c.append(a["__superclass_Prelude.Semigroup_0"]())(b)(d(e))}})(e.mempty(a))}},function(){return function(a){return function(c){return function(b){var e=a,f=c,u=b;a:for(;;){if(u instanceof d)return f;if(u instanceof g){b=e;f=e(f)(u.value0);u=u.value1;e=b;continue a}throw Error("Failed pattern match: "+
[e.constructor.name,f.constructor.name,u.constructor.name]);}}}}}(),function(a){return function(c){return function(e){if(e instanceof d)return c;if(e instanceof g)return a(e.value0)(b.foldr(f)(a)(c)(e.value1));throw Error("Failed pattern match: "+[a.constructor.name,c.constructor.name,e.constructor.name]);}}}),r=new c.Apply(function(){return l},function(a){return function(b){if(a instanceof d)return d.value;if(a instanceof g)return c["<>"](k)(c["<$>"](l)(a.value0)(b))(c["<*>"](r)(a.value1)(b));throw Error("Failed pattern match: "+
[a.constructor.name,b.constructor.name]);}}),w=new c.Applicative(function(){return r},function(a){return new g(a,d.value)});a.Nil=d;a.Cons=g;a.toList=function(a){return t(a)};a.reverse=p;a[":"]=h;a.fromFoldable=t;a.semigroupList=k;a.functorList=l;a.foldableList=f;a.applyList=r;a.applicativeList=w})(PS["Data.List"]=PS["Data.List"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Foldable"],e=PS["Data.List"],d=PS["Data.Maybe"],g=function(){function a(){}a.value=new a;return a}(),h=function(){function a(c,b,d,e){this.value0=c;this.value1=b;this.value2=d;this.value3=e}a.create=function(c){return function(b){return function(d){return function(e){return new a(c,b,d,e)}}}};return a}(),k=function(){function a(c,b,d,e,f,g,h){this.value0=c;this.value1=b;this.value2=d;this.value3=e;this.value4=f;this.value5=g;this.value6=h}a.create=function(c){return function(b){return function(d){return function(e){return function(f){return function(g){return function(h){return new a(c,
b,d,e,f,g,h)}}}}}}};return a}(),p=function(){function a(c,b,d){this.value0=c;this.value1=b;this.value2=d}a.create=function(c){return function(b){return function(d){return new a(c,b,d)}}};return a}(),l=function(){function a(c,b,d){this.value0=c;this.value1=b;this.value2=d}a.create=function(c){return function(b){return function(d){return new a(c,b,d)}}};return a}(),t=function(){function a(c,b,d,e,f,g){this.value0=c;this.value1=b;this.value2=d;this.value3=e;this.value4=f;this.value5=g}a.create=function(c){return function(b){return function(d){return function(e){return function(f){return function(g){return new a(c,
b,d,e,f,g)}}}}}};return a}(),f=function(){function a(c,b,d,e,f,g){this.value0=c;this.value1=b;this.value2=d;this.value3=e;this.value4=f;this.value5=g}a.create=function(c){return function(b){return function(d){return function(e){return function(f){return function(g){return new a(c,b,d,e,f,g)}}}}}};return a}(),r=function(){function a(c,b,d,e,f,g){this.value0=c;this.value1=b;this.value2=d;this.value3=e;this.value4=f;this.value5=g}a.create=function(c){return function(b){return function(d){return function(e){return function(f){return function(g){return new a(c,
b,d,e,f,g)}}}}}};return a}(),w=function(){function a(c,b,d,e){this.value0=c;this.value1=b;this.value2=d;this.value3=e}a.create=function(c){return function(b){return function(d){return function(e){return new a(c,b,d,e)}}}};return a}(),x=function(a){if(a instanceof g)return e.Nil.value;if(a instanceof h)return c["++"](e.semigroupList)(x(a.value0))(c["++"](e.semigroupList)(c.pure(e.applicativeList)(a.value1))(x(a.value3)));if(a instanceof k)return c["++"](e.semigroupList)(x(a.value0))(c["++"](e.semigroupList)(c.pure(e.applicativeList)(a.value1))(c["++"](e.semigroupList)(x(a.value3))(c["++"](e.semigroupList)(c.pure(e.applicativeList)(a.value4))(x(a.value6)))));
throw Error("Failed pattern match: "+[a.constructor.name]);},y=function(a){return function(a){return function(c){var b=a,d=c;a:for(;;){if(b instanceof e.Nil)return d;if(b instanceof e.Cons&&b.value0 instanceof p){c=b.value1;d=new h(d,b.value0.value0,b.value0.value1,b.value0.value2);b=c;continue a}if(b instanceof e.Cons&&b.value0 instanceof l){c=b.value1;d=new h(b.value0.value0,b.value0.value1,b.value0.value2,d);b=c;continue a}if(b instanceof e.Cons&&b.value0 instanceof t){c=b.value1;d=new k(d,b.value0.value0,
b.value0.value1,b.value0.value2,b.value0.value3,b.value0.value4,b.value0.value5);b=c;continue a}if(b instanceof e.Cons&&b.value0 instanceof f){c=b.value1;d=new k(b.value0.value0,b.value0.value1,b.value0.value2,d,b.value0.value3,b.value0.value4,b.value0.value5);b=c;continue a}if(b instanceof e.Cons&&b.value0 instanceof r){c=b.value1;d=new k(b.value0.value0,b.value0.value1,b.value0.value2,b.value0.value3,b.value0.value4,b.value0.value5,d);b=c;continue a}throw Error("Failed pattern match: "+[b.constructor.name,
d.constructor.name]);}}}},q=function(a){var b=function(a){return function(c){return function(b){var d=a,g=c,u=b;a:for(;;){if(g instanceof e.Nil)return new h(u.value0,u.value1,u.value2,u.value3);if(g instanceof e.Cons&&g.value0 instanceof p)return y(d)(g.value1)(new k(u.value0,u.value1,u.value2,u.value3,g.value0.value0,g.value0.value1,g.value0.value2));if(g instanceof e.Cons&&g.value0 instanceof l)return y(d)(g.value1)(new k(g.value0.value0,g.value0.value1,g.value0.value2,u.value0,u.value1,u.value2,
u.value3));if(g instanceof e.Cons&&g.value0 instanceof t){b=g.value1;u=new w(new h(u.value0,u.value1,u.value2,u.value3),g.value0.value0,g.value0.value1,new h(g.value0.value2,g.value0.value3,g.value0.value4,g.value0.value5));g=b;continue a}if(g instanceof e.Cons&&g.value0 instanceof f){b=g.value1;u=new w(new h(g.value0.value0,g.value0.value1,g.value0.value2,u.value0),u.value1,u.value2,new h(u.value3,g.value0.value3,g.value0.value4,g.value0.value5));g=b;continue a}if(g instanceof e.Cons&&g.value0 instanceof
r){b=g.value1;u=new w(new h(g.value0.value0,g.value0.value1,g.value0.value2,g.value0.value3),g.value0.value4,g.value0.value5,new h(u.value0,u.value1,u.value2,u.value3));g=b;continue a}throw Error("Failed pattern match at Data.Map line 147, column 1 - line 148, column 1: "+[g.constructor.name,u.constructor.name]);}}}};return function(a){return function(d){return function(q){return function(x){return function(m){var v=a,z=d,A=q,H=x;a:for(;;){if(m instanceof g)return b(v)(z)(new w(g.value,A,H,g.value));
if(m instanceof h&&c["=="](v["__superclass_Prelude.Eq_0"]())(A)(m.value1))return y(v)(z)(new h(m.value0,A,H,m.value3));if(m instanceof h&&c["<"](v)(A)(m.value1)){z=new e.Cons(new p(m.value1,m.value2,m.value3),z);m=m.value0;continue a}if(m instanceof h){z=new e.Cons(new l(m.value0,m.value1,m.value2),z);m=m.value3;continue a}if(m instanceof k&&c["=="](v["__superclass_Prelude.Eq_0"]())(A)(m.value1))return y(v)(z)(new k(m.value0,A,H,m.value3,m.value4,m.value5,m.value6));if(m instanceof k&&c["=="](v["__superclass_Prelude.Eq_0"]())(A)(m.value4))return y(v)(z)(new k(m.value0,
m.value1,m.value2,m.value3,A,H,m.value6));if(m instanceof k&&c["<"](v)(A)(m.value1)){z=new e.Cons(new t(m.value1,m.value2,m.value3,m.value4,m.value5,m.value6),z);m=m.value0;continue a}if(m instanceof k&&c["<"](v)(m.value1)(A)&&c["<="](v)(A)(m.value4)){z=new e.Cons(new f(m.value0,m.value1,m.value2,m.value4,m.value5,m.value6),z);m=m.value3;continue a}if(m instanceof k){z=new e.Cons(new r(m.value0,m.value1,m.value2,m.value3,m.value4,m.value5),z);m=m.value6;continue a}throw Error("Failed pattern match at Data.Map line 147, column 1 - line 148, column 1: "+
[z.constructor.name,A.constructor.name,H.constructor.name,m.constructor.name]);}}}}}}(a)(e.Nil.value)},v=g.value;a.keys=x;a.fromList=function(a){return b.foldl(e.foldableList)(function(c){return function(b){return q(a)(b.value0)(b.value1)(c)}})(v)};a.lookup=function(a){return function(b){return function(e){var f=a,l=b;a:for(;;){if(e instanceof g)return d.Nothing.value;if(e instanceof h&&c["=="](f["__superclass_Prelude.Eq_0"]())(l)(e.value1))return new d.Just(e.value2);if(e instanceof h&&c["<"](f)(l)(e.value1)){e=
e.value0;continue a}if(e instanceof h){e=e.value3;continue a}if(e instanceof k&&c["=="](f["__superclass_Prelude.Eq_0"]())(l)(e.value1))return new d.Just(e.value2);if(e instanceof k&&c["=="](f["__superclass_Prelude.Eq_0"]())(l)(e.value4))return new d.Just(e.value5);if(e instanceof k&&c["<"](f)(l)(e.value1)){e=e.value0;continue a}if(e instanceof k&&c["<"](f)(e.value1)(l)&&c["<="](f)(l)(e.value4)){e=e.value3;continue a}if(e instanceof k){e=e.value6;continue a}throw Error("Failed pattern match: "+[l.constructor.name,
e.constructor.name]);}}}};a.insert=q;a.empty=v})(PS["Data.Map"]=PS["Data.Map"]||{});(function(a){a["regex'"]=function(a){return function(b){return new RegExp(a,b)}};a._match=function(a){return function(b){return function(e){return function(d){d=d.match(e);if(null==d)return b;for(var g=[],h=0;h<d.length;h++)g.push(null==d[h]?b:a(d[h]));return a(g)}}}}})(PS["Data.String.Regex"]=PS["Data.String.Regex"]||{});
(function(a){var c=PS["Data.String.Regex"],b=PS["Data.Maybe"],e=PS["Data.String"],d=function(a){var c;if(a.global)c="g";else{if(a.global)throw Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: "+[a.global.constructor.name]);c=""}var b;if(a.ignoreCase)b="i";else{if(a.ignoreCase)throw Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: "+[a.ignoreCase.constructor.name]);b=""}var d;if(a.multiline)d="m";else{if(a.multiline)throw Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: "+
[a.multiline.constructor.name]);d=""}var e;if(a.sticky)e="y";else{if(a.sticky)throw Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: "+[a.sticky.constructor.name]);e=""}if(a.unicode)a="u";else{if(a.unicode)throw Error("Failed pattern match at Data.String.Regex line 63, column 1 - line 64, column 1: "+[a.unicode.constructor.name]);a=""}return c+(b+(d+(e+a)))},b=c._match(b.Just.create)(b.Nothing.value);a.match=b;a.parseFlags=function(a){return{global:e.contains("g")(a),
ignoreCase:e.contains("i")(a),multiline:e.contains("m")(a),sticky:e.contains("y")(a),unicode:e.contains("u")(a)}};a.renderFlags=d;a.regex=function(a){return function(b){return c["regex'"](a)(d(b))}}})(PS["Data.String.Regex"]=PS["Data.String.Regex"]||{});
(function(a){function c(){void 0===window.flareID&&(window.flareID=0);window.flareID+=1;return"flare-component-"+window.flareID.toString()}function b(a,b,g,h){return function(k){return function(p){return function(l){return function(){var t=c(),f=b(p);f.className="flare-input-"+a;f.id=t;var r=document.createElement("div");r.className="flare-input";if(""!==k){var w=document.createElement("label");w.htmlFor=t;w.appendChild(document.createTextNode(k));r.appendChild(w)}r.appendChild(f);f.addEventListener(g,
function(a){a=h(a.target,p);l(a)()});return r}}}}}a.cNumber=b("number",function(a){var c=document.createElement("input");c.type="number";c.step="any";c.value=a.toString();return c},"input",function(a,c){var b=parseFloat(a.value);return isNaN(b)?c:b});a.cNumberRange=function(a){return function(c){return function(g){return function(h){return b("number-"+a,function(b){var p=document.createElement("input");p.type=a;p.min=c.toString();p.max=g.toString();p.step=h.toString();p.value=b.toString();return p},
"input",function(a,b){var e=parseFloat(a.value);return isNaN(e)?b:e<c?c:e>g?g:e})}}}};a.cIntRange=function(a){return function(c){return function(g){return b("int-"+a,function(b){var k=document.createElement("input");k.type=a;k.min=c.toString();k.max=g.toString();k.step="1";k.value=b.toString();return k},"input",function(a,b){var e=parseInt(a.value,10);return isNaN(e)?b:e<c?c:e>g?g:e})}}};a.cString=b("string",function(a){var c=document.createElement("input");c.type="text";c.value=a;return c},"input",
function(a,c){return a.value});a.cStringPattern=function(a){return b("string-pattern",function(c){var b=document.createElement("input");b.type="text";b.pattern=a;b.required=!0;b.value=c;return b},"input",function(a,c){return a.value})};a.cBoolean=b("boolean",function(a){var c=document.createElement("input");c.type="checkbox";c.checked=a;return c},"change",function(a,c){return a.checked});a.cSelect=function(a){return function(c){return b("select",function(b){for(var h=document.createElement("select"),
k,p,l=0;l<a.length+1;l++)k=0===l?b:a[l-1],p=document.createElement("option"),p.appendChild(document.createTextNode(c(k))),h.appendChild(p);return h},"change",function(c,b){var d=c.selectedIndex;return 0===d?b:a[d-1]})}};a.cRadioGroup=function(a){return function(d){return function(g){var h=c();return b("radioGroup",function(c){var b=document.createElement("fieldset");if(""!==g){var l=document.createElement("legend");l.appendChild(document.createTextNode(g));b.appendChild(l)}for(var t,f,r=0;r<a.length+
1;r++)l=0===r?c:a[r-1],t=h+"-"+r.toString(),f=document.createElement("input"),f.type="radio",f.name=h,f.id=t,0===r&&(f.checked="checked"),b.appendChild(f),f=document.createElement("label"),f.appendChild(document.createTextNode(d(l))),f.htmlFor=t,b.appendChild(f);return b},"change",function(c,b){var d=parseInt(c.id.substr(h.length+1),10);return 0===d?b:a[d-1]})("")}}};a.toFieldset=function(a){return function(c){var b=document.createElement("fieldset");if(""!==a){var h=document.createElement("legend");
h.appendChild(document.createTextNode(a));b.appendChild(h)}for(h=0;h<c.length;h++)b.appendChild(c[h]);return b}}})(PS.Flare=PS.Flare||{});
(function(a){a.constant=function(a){var b=[],e=a;return{subscribe:function(a){b.push(a);a(e)},get:function(){return e},set:function(a){e=a;b.forEach(function(c){c(a)})}}};a.mapSigP=function(a){return function(b){return function(e){var d=a(b(e.get()));e.subscribe(function(a){d.set(b(a))});return d}}};a.applySigP=function(a){return function(b){return function(e){var d=a(b.get()(e.get())),g=function(){d.set(b.get()(e.get()))};b.subscribe(g);e.subscribe(g);return d}}};a.runSignal=function(a){return function(){a.subscribe(function(a){a()});
return{}}}})(PS.Signal=PS.Signal||{});(function(a){var c=PS.Signal,b=PS.Prelude,e=c.mapSigP(c.constant),d=new b.Functor(e),e=c.applySigP(c.constant),g=new b.Apply(function(){return d},e),b=new b.Applicative(function(){return g},c.constant);a.functorSignal=d;a.applySignal=g;a.applicativeSignal=b;a.runSignal=c.runSignal;a.constant=c.constant})(PS.Signal=PS.Signal||{});
(function(a){a.channelP=function(a){return function(b){return function(){return a(b)}}};a.sendP=function(a,b){return function(b){return function(){a.set(b)}}};a.subscribe=function(a){return a}})(PS["Signal.Channel"]=PS["Signal.Channel"]||{});(function(a){var c=PS["Signal.Channel"],b=c.sendP,e=c.channelP(PS.Signal.constant);a.send=b;a.channel=e;a.subscribe=c.subscribe})(PS["Signal.Channel"]=PS["Signal.Channel"]||{});
(function(a){var c=PS.Flare,b=PS.Prelude,e=PS["Control.Apply"],d=PS["Control.Monad.Eff"],g=PS.Signal,h=PS["Signal.Channel"],k=function(){function a(c,b){this.value0=c;this.value1=b}a.create=function(c){return function(b){return new a(c,b)}};return a}(),p=function(a){return a},l=new b.Functor(function(a){return function(c){return new k(c.value0,b.map(g.functorSignal)(a)(c.value1))}}),t=new b.Functor(function(a){return function(c){return p(b.map(d.functorEff)(b.map(l)(a))(c))}}),f=function(a){return function(c){return function(b){return p(function(){var d=
h.channel(b)(),e=a(c)(b)(h.send(d))(),d=h.subscribe(d);return new k([e],d)})}}},r=f(c.cNumber),w=f(c.cString),x=f(c.cBoolean),y=new b.Apply(function(){return l},function(a){return function(c){return new k(b["<>"](b.semigroupArray)(a.value0)(c.value0),b["<*>"](g.applySignal)(a.value1)(c.value1))}}),q=new b.Apply(function(){return t},function(a){return function(c){return p(e.lift2(d.applyEff)(b.apply(y))(a)(c))}}),v=new b.Applicative(function(){return y},function(a){return new k([],b.pure(g.applicativeSignal)(a))}),
B=new b.Applicative(function(){return q},function(a){return p(b["return"](d.applicativeEff)(b.pure(v)(a)))});a.setupFlare=function(a){return function(){var c=a();return{components:c.value0,signal:c.value1}}};a.fieldset=function(a){return function(b){return p(function(){var d=b();return new k([c.toFieldset(a)(d.value0)],d.value1)})}};a.radioGroup=function(a){return function(b){return function(d){return function(e){return f(c.cRadioGroup(d)(e))(a)(b)}}}};a.select=function(a){return function(b){return function(d){return function(e){return f(c.cSelect(d)(e))(a)(b)}}}};
a["boolean"]=x;a.stringPattern=function(a){return function(b){return function(d){return f(c.cStringPattern(b))(a)(d)}}};a.string=w;a.intSlider=function(a){return function(b){return function(d){return function(e){return f(c.cIntRange("range")(b)(d))(a)(e)}}}};a.intRange=function(a){return function(b){return function(d){return function(e){return f(c.cIntRange("number")(b)(d))(a)(e)}}}};a["int"]=function(a){return f(c.cIntRange("number")(b.bottom(b.boundedInt))(b.top(b.boundedInt)))(a)};a.numberSlider=
function(a){return function(b){return function(d){return function(e){return function(g){return f(c.cNumberRange("range")(b)(d)(e))(a)(g)}}}}};a.number=r;a.functorFlare=l;a.applyFlare=y;a.applicativeFlare=v;a.functorUI=t;a.applyUI=q;a.applicativeUI=B})(PS.Flare=PS.Flare||{});
(function(a){a.appendTest=function(a){return function(b){return function(e){return function(d){return function(){var g=document.getElementById(a),h=document.createElement("fieldset");h.className="flarecheck-test";var k=document.createElement("legend");k.textContent=b;h.appendChild(k);""!==e&&(k=document.createElement("p"),k.innerHTML=e,h.appendChild(k));for(k=0;k<d.length;k++)h.appendChild(d[k]);k=document.createElement("div");k.className="flarecheck-output";h.appendChild(k);g.appendChild(h);return k}}}}};
a.escapeHTML=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};a.setText=function(a){return function(b){return function(){var e=a.firstChild;e||(e=document.createElement("pre"),e.className="flarecheck-output-settext",a.appendChild(e));e.textContent=b}}};a.setHTML=function(a){return function(b){return function(){a.innerHTML=b}}}})(PS["Test.FlareCheck"]=PS["Test.FlareCheck"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Maybe"],e=PS["Data.Monoid"],d=PS["Control.Apply"],g=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),h=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),k=function(){function a(b,c,d,e){this.value0=b;this.value1=c;this.value2=d;this.value3=e}a.create=function(b){return function(c){return function(d){return function(e){return new a(b,c,d,e)}}}};
return a}(),p=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),l=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),t=function(a){this["with"]=a},f=new c.Functor(function(a){return function(b){if(b instanceof k)return new k(b.value0,b.value1,b.value2,c.map(f)(a)(b.value3));if(b instanceof p)return new p(b.value0,c.map(f)(a)(b.value1));if(b instanceof l)return new l(a(b.value0));throw Error("Failed pattern match: "+
[a.constructor.name,b.constructor.name]);}}),r=new t(function(a){return function(b){if(a instanceof k)return new k(a.value0,a.value1,c["<>"](c.semigroupArray)(a.value2)(b.value0),a.value3);throw Error("Failed pattern match at Text.Smolder.Markup line 79, column 1 - line 82, column 1: "+[a.constructor.name,b.constructor.name]);}}),w=new t(function(a){return function(b){return function(c){return(0,r["with"])(a(c))(b)}}}),x=new c.Monad(function(){return v},function(){return y}),y=new c.Bind(function(){return q},
function(a){return function(b){if(a instanceof k)return new k(a.value0,a.value1,a.value2,c.bind(y)(a.value3)(b));if(a instanceof p)return new p(a.value0,c.bind(y)(a.value1)(b));if(a instanceof l)return b(a.value0);throw Error("Failed pattern match: "+[a.constructor.name,b.constructor.name]);}}),q=new c.Apply(function(){return f},c.ap(x)),v=new c.Applicative(function(){return q},l.create),B=new c.Semigroup(function(a){return function(b){return d["*>"](q)(a)(b)}}),e=new e.Monoid(function(){return B},
new l(c.unit));a.Attr=g;a.Element=k;a.Content=p;a.Return=l;a.Attributable=t;a["!"]=function(a){return a["with"]};a.attribute=function(a){return function(b){return new h([new g(a,b)])}};a.text=function(a){return new p(a,new l(c.unit))};a.parent=function(a){return function(d){return new k(a,new b.Just(d),[],new l(c.unit))}};a.semigroupMarkupM=B;a.monoidMarkup=e;a.functorMarkupM=f;a.applyMarkupM=q;a.applicativeMarkupM=v;a.bindMarkupM=y;a.monadMarkupM=x;a.attributableMarkupM=r;a.attributableMarkupMF=
w})(PS["Text.Smolder.Markup"]=PS["Text.Smolder.Markup"]||{});(function(a){var c=PS["Text.Smolder.Markup"],b=c.parent("span"),c=c.parent("pre");a.span=b;a.pre=c})(PS["Text.Smolder.HTML"]=PS["Text.Smolder.HTML"]||{});(function(a){var c=PS["Text.Smolder.Markup"],b=c.attribute("title"),c=c.attribute("class");a.title=b;a.className=c})(PS["Text.Smolder.HTML.Attributes"]=PS["Text.Smolder.HTML.Attributes"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Maybe"],e=PS["Data.Tuple"],d=PS["Data.List"],g=PS["Data.Map"],h=PS["Text.Smolder.Markup"],k=PS["Data.Foldable"],p=function(){function a(b,c,d){this.value0=b;this.value1=c;this.value2=d}a.create=function(b){return function(c){return function(d){return new a(b,c,d)}}};return a}(),l=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),t=function(){var a=function(a){return new e.Tuple(a.value0,a.value1)};return function(b){return g.fromList(c.ordString)(c.map(d.functorList)(a)(d.toList(k.foldableArray)(b)))}}(),
f=function(a){if(a instanceof h.Element&&a.value1 instanceof b.Just)return d[":"](new p(a.value0,t(a.value2),f(a.value1.value0)))(f(a.value3));if(a instanceof h.Element&&a.value1 instanceof b.Nothing)return d[":"](new p(a.value0,t(a.value2),d.Nil.value))(f(a.value3));if(a instanceof h.Content)return d[":"](new l(a.value0))(f(a.value1));if(a instanceof h.Return)return d.Nil.value;throw Error("Failed pattern match: "+[a.constructor.name]);};a.Element=p;a.Text=l;a.renderMarkup=f})(PS["Text.Smolder.Renderer.Util"]=
PS["Text.Smolder.Renderer.Util"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.List"],e=PS["Data.Foldable"],d=PS["Data.Map"],g=PS["Text.Smolder.Renderer.Util"],h=PS["Data.Monoid"],k=function(a){if(a instanceof g.Element)return"<"+(a.value0+(function(a){return e.fold(b.foldableList)(h.monoidString)(c.map(b.functorList)(function(b){return" "+(b+e.foldMap(e.foldableMaybe)(h.monoidString)(function(a){return'="'+(a+'"')})(d.lookup(c.ordString)(b)(a)))})(d.keys(a)))}(a.value1)+function(d){return d instanceof b.Nil?"/>":">"+(e.fold(b.foldableList)(h.monoidString)(c.map(b.functorList)(k)(d))+
("</"+(a.value0+">")))}(a.value2)));if(a instanceof g.Text)return a.value0;throw Error("Failed pattern match: "+[a.constructor.name]);};a.renderNode=k;a.render=function(a){return e.fold(b.foldableList)(h.monoidString)(c.map(b.functorList)(k)(g.renderMarkup(a)))}})(PS["Text.Smolder.Renderer.String"]=PS["Text.Smolder.Renderer.String"]||{});
(function(a){var c=PS["Test.FlareCheck"],b=PS.Prelude,e=PS["Data.Array"],d=PS["Data.Array.Unsafe"],g=PS["Data.Char"],h=PS["Data.Either"],k=PS["Data.Enum"],p=PS["Data.Foldable"],l=PS["Data.Generic"],t=PS["Data.Int"],f=PS["Data.List"],r=PS["Data.Maybe"],w=PS["Data.String"],x=PS["Data.Tuple"],y=PS["Type.Proxy"],q=PS["Text.Smolder.Markup"],v=PS["Text.Smolder.HTML"],B=PS["Text.Smolder.HTML.Attributes"],u=PS["Text.Smolder.Renderer.String"],J=PS.Signal,n=PS.Flare,K=function(a){return a},I=function(a){return a},
m=function(a){return a},D=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),z=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),A=function(a){return a},H=function(a){return a},C=function(a){this.spark=a},M=function(a,b,c){this.defaults=a;this.read=b;this.typeName=c},E=function(a){this.interactive=a},F=function(a){return q["!"](q.attributableMarkupMF)(q["!"](q.attributableMarkupMF)(v.span)(B.className("flarecheck-tooltip")))(B.title(a))},
G=function(a){return q.text(c.escapeHTML(a))},Q=function(a){return function(b){if(b instanceof D)return c.setText(a)(b.value0);if(b instanceof z)return c.setHTML(a)(u.render(b.value0));throw Error("Failed pattern match at Test.FlareCheck line 370, column 1 - line 373, column 1: "+[a.constructor.name,b.constructor.name]);}},R=new M(function(a){return"foo,bar,baz"},r.Just.create,function(a){return"String"}),t=new M(function(a){return"0,1,2"},t.fromString,function(a){return"Int"}),L=function(a){return function(b){return q["!"](q.attributableMarkupMF)(v.span)(B.className("flarecheck-"+
a))(G(b))}},T=function(a){return function(d){return function(e){return function(f){return function(g){var h=(0,a.interactive)(b.pure(n.applicativeUI)(g));return function(){var a=n.setupFlare(h)(),g=r.fromMaybe("")(f),g=c.appendTest(d)(e)(g)(a.components)();return J.runSignal(b["<$>"](J.functorSignal)(Q(g))(a.signal))()}}}}}},P=new C(n.string("String")("foo")),S=new C(b["<$>"](n.functorUI)(I)(n.numberSlider("Number")(0)(1)(1E-5)(.5))),Y=new C(b["<$>"](n.functorUI)(m)(n.intSlider("Int")(0)(100)(1))),
Z=new C(n.number("Number")(3.14)),aa=new C(b["<$>"](n.functorUI)(A)(n.intRange("Int")(0)(b.top(b.boundedInt))(1))),ba=new C(function(){return b["<$>"](n.functorUI)(b["<$>"](b.functorFn)(H)(function(a){return w.joinWith("\n")(w.split("\\n")(a))}))(n.string("String")("foo\\nbar"))}()),ca=new C(n["int"]("Int")(1)),da=new C(b["<$>"](n.functorUI)(b["<$>"](b.functorFn)(r.fromMaybe(" "))(w.charAt(0)))(n.stringPattern("Char")("^.$")("f"))),ea=new C(n["boolean"]("Boolean")(!1)),V=function(a){var c=(0,a.defaults)(y.Proxy.value);
return b["<$>"](n.functorUI)(function(c){return e.catMaybes(b.map(b.functorArray)(a.read)(w.split(",")(c)))})(n.string("CSV:")(c))},W=function(a){var b=w.split(".")(a),c=d.last(b);if(b=1===e.length(b))a="Data constructor form unknown module";else if(b)throw Error("Failed pattern match at Test.FlareCheck line 222, column 1 - line 223, column 1: "+[b.constructor.name]);return F(a)(L("constructor")(c))},U=function(a){return function(c){if(c instanceof l.SProd){var d=function(a){return function(c){if(!a)return c;
if(a)return b.bind(q.bindMarkupM)(G("("))(function(){return b.bind(q.bindMarkupM)(c)(function(){return G(")")})});throw Error("Failed pattern match at Test.FlareCheck line 244, column 9 - line 245, column 9: "+[a.constructor.name,c.constructor.name]);}},f=e["null"](c.value1);if(f)return W(c.value0);if(!f)return d(10<a)(b.bind(q.bindMarkupM)(W(c.value0))(function(){return p.for_(q.applicativeMarkupM)(p.foldableArray)(c.value1)(function(a){return b.bind(q.bindMarkupM)(G(" "))(function(){return U(11)(a(b.unit))})})}));
throw Error("Failed pattern match: "+[f.constructor.name]);}if(c instanceof l.SRecord){var h=function(a){return b.bind(q.bindMarkupM)(L("record-field")(a.recLabel))(function(){return b.bind(q.bindMarkupM)(G(": "))(function(){return U(0)(a.recValue(b.unit))})})};return b.bind(q.bindMarkupM)(G("{ "))(function(){return b.bind(q.bindMarkupM)(p.intercalate(p.foldableArray)(q.monoidMarkup)(G(", "))(b.map(b.functorArray)(h)(c.value0)))(function(){return G(" }")})})}if(c instanceof l.SBoolean)return F("Boolean")(L("boolean")(b.show(b.showBoolean)(c.value0)));
if(c instanceof l.SNumber)return F("Number")(L("number")(b.show(b.showNumber)(c.value0)));if(c instanceof l.SInt)return F("Int")(L("number")(b.show(b.showInt)(c.value0)));if(c instanceof l.SString)return d="String of length "+b.show(b.showInt)(w.length(c.value0)),F(d)(L("string")(b.show(b.showString)(c.value0)));if(c instanceof l.SChar)return d="Char (with char code "+(b.show(b.showInt)(g.toCharCode(c.value0))+")"),F(d)(L("string")(b.show(b.showChar)(c.value0)));if(c instanceof l.SArray)return d=
"Array of length "+b.show(b.showInt)(e.length(c.value0)),F(d)(b.bind(q.bindMarkupM)(G("["))(function(){return b.bind(q.bindMarkupM)(p.intercalate(p.foldableArray)(q.monoidMarkup)(G(", "))(b.map(b.functorArray)(function(a){return U(0)(a(b.unit))})(c.value0)))(function(){return G("]")})}));throw Error("Failed pattern match: "+[a.constructor.name,c.constructor.name]);}},fa=U(0),O=function(a){return function(b){return fa(l.toSpine(a)(b))}},ga=new E(function(){var a=function(a){if(a)return"flarecheck-okay";
if(!a)return"flarecheck-warn";throw Error("Failed pattern match at Test.FlareCheck line 302, column 7 - line 304, column 1: "+[a.constructor.name]);},c=function(b){return q["!"](q.attributableMarkupMF)(v.pre)(B.className(a(b)))(O(l.genericBool)(b))};return b.map(n.functorUI)(function(a){return z.create(c(a))})}()),X=function(a){return function(c){var d=function(d){return b.bind(q.bindMarkupM)(G("fromFoldable "))(function(){return O(l.genericArray(c))(p.foldl(a)(e.snoc)([])(d))})};return b.map(n.functorUI)(function(a){return z.create(v.pre(d(a)))})}},
N=function(a){return function(c){return b["<$>"](n.functorUI)(function(b){return z.create(v.pre(O(a)(b)))})(c)}},ha=new E(N(l.genericChar)),ia=new E(N(l.genericInt)),ja=new E(N(l.genericNumber)),ka=new E(N(l.genericString));a.SetText=D;a.SetHTML=z;a.WrapEnum=K;a.Multiline=H;a.SmallNumber=I;a.SmallInt=m;a.NonNegativeInt=A;a.Interactive=E;a.Read=M;a.Flammable=C;a["flareCheck'"]=function(a){return function(b){return function(c){return T(a)(b)(c)(r.Nothing.value)}}};a.interactiveFoldable=X;a.interactiveGeneric=
N;a.interactive=function(a){return a.interactive};a.read=function(a){return a.read};a.defaults=function(a){return a.defaults};a.typeName=function(a){return a.typeName};a.spark=function(a){return a.spark};a.flammableNumber=Z;a.flammableInt=ca;a.flammableString=P;a.flammableChar=da;a.flammableBoolean=ea;a.flammableTuple=function(a){return function(c){return new C(n.fieldset("Tuple")(b["<*>"](n.applyUI)(b["<$>"](n.functorUI)(x.Tuple.create)(a.spark))(c.spark)))}};a.flammableMaybe=function(a){return new C(function(){return n.fieldset("Maybe")(b["<*>"](n.applyUI)(b["<$>"](n.functorUI)(function(a){return function(b){if(a)return new r.Just(b);
if(!a)return r.Nothing.value;throw Error("Failed pattern match at Test.FlareCheck line 88, column 11 - line 89, column 11: "+[a.constructor.name,b.constructor.name]);}})(n["boolean"]("Just")(!0)))(a.spark))}())};a.flammableEither=function(a){return function(c){return new C(function(){return n.fieldset("Either")(b["<*>"](n.applyUI)(b["<*>"](n.applyUI)(b["<$>"](n.functorUI)(function(a){return function(b){return function(c){return"Left"===a?new h.Left(b):new h.Right(c)}}})(n.radioGroup("Select:")("Left")(["Right"])(b.id(b.categoryFn))))(a.spark))(c.spark))}())}};
a.flammableNonNegativeInt=aa;a.flammableSmallInt=Y;a.flammableSmallNumber=S;a.flammableMultiline=ba;a.flammableWrapEnum=function(a){return function(c){return new C(function(){var d=function(b){return r.maybe([])(function(a){return e.cons(a)(d(a))})(k.succ(a)(b))};return b["<$>"](n.functorUI)(K)(n.select("Enum")(b.bottom(a["__superclass_Prelude.Bounded_0"]()))(d(b.bottom(a["__superclass_Prelude.Bounded_0"]())))(b.show(c)))}())}};a.readInt=t;a.readString=R;a.flammableArrayRead=function(a){var b=(0,a.typeName)(y.Proxy.value);
a=n.fieldset("Array "+b)(V(a));return new C(a)};a.flammableListRead=function(a){var c=(0,a.typeName)(y.Proxy.value);a=n.fieldset("List "+c)(b["<$>"](n.functorUI)(f.toList(p.foldableArray))(V(a)));return new C(a)};a.interactiveNumber=ja;a.interactiveInt=ia;a.interactiveString=ka;a.interactiveChar=ha;a.interactiveBoolean=ga;a.interactiveMaybe=function(a){return new E(function(){var c=function(b){return q["!"](q.attributableMarkupMF)(v.pre)(B.className(b instanceof r.Nothing?"flarecheck-warn":""))(O(l.genericMaybe(a))(b))};
return b.map(n.functorUI)(function(a){return z.create(c(a))})}())};a.interactiveEither=function(a){return function(c){return new E(function(){var d=function(b){return q["!"](q.attributableMarkupMF)(v.pre)(B.className(b instanceof h.Left?"flarecheck-warn":""))(O(l.genericEither(a)(c))(b))};return b.map(n.functorUI)(function(a){return z.create(d(a))})}())}};a.interactiveTuple=function(a){return function(b){return new E(N(l.genericTuple(a)(b)))}};a.interactiveArray=function(a){return new E(function(){var c=
function(b){return q["!"](q.attributableMarkupMF)(v.pre)(B.className(0===b.length?"flarecheck-warn":""))(O(l.genericArray(a))(b))};return b.map(n.functorUI)(function(a){return z.create(c(a))})}())};a.interactiveList=function(a){return new E(X(f.foldableList)(a))};a.interactiveWrapEnum=function(a){return new E(function(){var c=function(a){return a};return function(d){return N(a)(b.map(n.functorUI)(c)(d))}}())};a.interactiveFunction=function(a){return function(c){return new E(function(d){return(0,c.interactive)(b["<*>"](n.applyUI)(d)(a.spark))})}}})(PS["Test.FlareCheck"]=
PS["Test.FlareCheck"]||{});
(function(a){var c=PS.Prelude,b=PS["Data.Array"],e=PS["Data.Enum"],d=PS["Data.Generic"],g=PS["Data.Int"],h=PS["Data.Maybe"],k=PS["Data.String"],p=PS["Data.String.Regex"],l=PS["Data.Tuple"],t=PS.Flare,f=PS["Test.FlareCheck"],r=function(){function a(){}a.value=new a;return a}(),w=function(){function a(){}a.value=new a;return a}(),x=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),y=function(a){return a},q=function(a){return a},v=function(a){return 0===a?new h.Just(r.value):
1===a?new h.Just(w.value):2===a?h.Just.create(new x(!1)):3===a?h.Just.create(new x(!0)):h.Nothing.value},B=function(a){if(a instanceof r)return 0;if(a instanceof w)return 1;if(a instanceof x&&!a.value0)return 2;if(a instanceof x&&a.value0)return 3;throw Error("Failed pattern match at Test.Main line 47, column 1 - line 48, column 1: "+[a.constructor.name]);},u=new d.Generic(function(a){return a instanceof d.SProd&&"Test.Main.Option1"===a.value0&&0===a.value1.length?new h.Just(r.value):a instanceof
d.SProd&&"Test.Main.Option2"===a.value0&&0===a.value1.length?new h.Just(w.value):a instanceof d.SProd&&"Test.Main.TrueOrFalse"===a.value0&&1===a.value1.length?c.apply(h.applyMaybe)(new h.Just(x.create))(d.fromSpine(d.genericBool)(a.value1[0](c.unit))):h.Nothing.value},function(a){return new d.SigProd("Test.Main.TestEnum",[{sigConstructor:"Test.Main.Option1",sigValues:[]},{sigConstructor:"Test.Main.Option2",sigValues:[]},{sigConstructor:"Test.Main.TrueOrFalse",sigValues:[function(a){return d.toSignature(d.genericBool)(d.anyProxy)}]}])},
function(a){if(a instanceof r)return new d.SProd("Test.Main.Option1",[]);if(a instanceof w)return new d.SProd("Test.Main.Option2",[]);if(a instanceof x)return new d.SProd("Test.Main.TrueOrFalse",[function(b){return d.toSpine(d.genericBool)(a.value0)}]);throw Error("Failed pattern match at Test.Main line 42, column 1 - line 44, column 1: "+[a.constructor.name]);}),J=new c.Show(d.gShow(u)),n=new d.Generic(function(a){return a instanceof d.SProd&&"Test.Main.Foo"===a.value0&&1===a.value1.length?c.apply(h.applyMaybe)(new h.Just(q))(function(a){return a instanceof
d.SRecord&&5===a.value0.length?c.apply(h.applyMaybe)(c.apply(h.applyMaybe)(c.apply(h.applyMaybe)(c.apply(h.applyMaybe)(c.apply(h.applyMaybe)(new h.Just(function(a){return function(b){return function(c){return function(d){return function(e){return{arr:a,bool:b,num:c,optional:d,str:e}}}}}}))(d.fromSpine(d.genericArray(d.genericInt))(a.value0[0].recValue(c.unit))))(d.fromSpine(d.genericBool)(a.value0[1].recValue(c.unit))))(d.fromSpine(d.genericNumber)(a.value0[2].recValue(c.unit))))(d.fromSpine(d.genericMaybe(d.genericChar))(a.value0[3].recValue(c.unit))))(d.fromSpine(d.genericString)(a.value0[4].recValue(c.unit))):
h.Nothing.value}(a.value1[0](c.unit))):h.Nothing.value},function(a){return new d.SigProd("Test.Main.Foo",[{sigConstructor:"Test.Main.Foo",sigValues:[function(a){return new d.SigRecord([{recLabel:"arr",recValue:function(a){return d.toSignature(d.genericArray(d.genericInt))(d.anyProxy)}},{recLabel:"bool",recValue:function(a){return d.toSignature(d.genericBool)(d.anyProxy)}},{recLabel:"num",recValue:function(a){return d.toSignature(d.genericNumber)(d.anyProxy)}},{recLabel:"optional",recValue:function(a){return d.toSignature(d.genericMaybe(d.genericChar))(d.anyProxy)}},
{recLabel:"str",recValue:function(a){return d.toSignature(d.genericString)(d.anyProxy)}}])}]}])},function(a){return new d.SProd("Test.Main.Foo",[function(b){return new d.SRecord([{recLabel:"arr",recValue:function(b){return d.toSpine(d.genericArray(d.genericInt))(a.arr)}},{recLabel:"bool",recValue:function(b){return d.toSpine(d.genericBool)(a.bool)}},{recLabel:"num",recValue:function(b){return d.toSpine(d.genericNumber)(a.num)}},{recLabel:"optional",recValue:function(b){return d.toSpine(d.genericMaybe(d.genericChar))(a.optional)}},
{recLabel:"str",recValue:function(b){return d.toSpine(d.genericString)(a.str)}}])}])}),K=new f.Interactive(f.interactiveGeneric(n)),I=new f.Flammable(t.fieldset("Regex")(c["<$>"](t.functorUI)(y)(c["<*>"](t.applyUI)(c["<$>"](t.functorUI)(p.regex)(t.string("Pattern")("fo+")))(c["<$>"](t.functorUI)(p.parseFlags)(t.string("Flags (g,i,m)")("g")))))),m=new c.Bounded(r.value,new x(!0)),D=new e.Enum(function(){return m},4,B,e.defaultPred(v)(B),e.defaultSucc(v)(B),v);a.Option1=r;a.Option2=w;a.TrueOrFalse=
x;a.Foo=q;a.TRegex=y;a.main=function(){f["flareCheck'"](f.interactiveFunction(f.flammableString)(f.interactiveInt))("tests1")("length")(k.length)();f["flareCheck'"](f.interactiveFunction(f.flammableInt)(f.interactiveFunction(f.flammableString)(f.interactiveMaybe(d.genericInt))))("tests1")("charCodeAt")(k.charCodeAt)();f["flareCheck'"](f.interactiveFunction(f.flammableString)(f.interactiveFunction(f.flammableArrayRead(f.readString))(f.interactiveString)))("tests1")("joinWith")(k.joinWith)();f["flareCheck'"](f.interactiveFunction(f.flammableArrayRead(f.readInt))(f.interactiveArray(d.genericInt)))("tests1")("filter even")(b.filter(g.even))();
f["flareCheck'"](f.interactiveFunction(f.flammableNumber)(f.interactiveFunction(f.flammableMaybe(f.flammableNumber))(f.interactiveNumber)))("tests1")("fromMaybe")(h.fromMaybe)();f["flareCheck'"](f.interactiveFunction(I)(f.interactiveFunction(f.flammableString)(f.interactiveMaybe(d.genericArray(d.genericMaybe(d.genericString))))))("tests2")("match")(function(a){return function(b){return p.match(a)(b)}})();var a=function(a){return f["flareCheck'"](a)("tests3")};a(f.interactiveFunction(f.flammableInt)(f.interactiveInt))("Int")(c.id(c.categoryFn))();
a(f.interactiveFunction(f.flammableNumber)(f.interactiveNumber))("Number")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableBoolean)(f.interactiveBoolean))("Boolean")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableString)(f.interactiveString))("String")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableChar)(f.interactiveChar))("Char")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableMaybe(f.flammableInt))(f.interactiveMaybe(d.genericInt)))("Maybe Int")(c.id(c.categoryFn))();
a(f.interactiveFunction(f.flammableMaybe(f.flammableString))(f.interactiveMaybe(d.genericString)))("Maybe String")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableEither(f.flammableString)(f.flammableInt))(f.interactiveEither(d.genericString)(d.genericInt)))("Either String Int")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableTuple(f.flammableInt)(f.flammableString))(f.interactiveTuple(d.genericInt)(d.genericString)))("Tuple Int String")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableArrayRead(f.readInt))(f.interactiveArray(d.genericInt)))("Array Int")(c.id(c.categoryFn))();
a(f.interactiveFunction(f.flammableArrayRead(f.readString))(f.interactiveArray(d.genericString)))("Array String")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableListRead(f.readInt))(f.interactiveList(d.genericInt)))("List Int")(c.id(c.categoryFn))();a(f.interactiveFunction(f.flammableListRead(f.readString))(f.interactiveList(d.genericString)))("List String")(c.id(c.categoryFn))();a(f.interactiveMaybe(d.genericTuple(d.genericInt)(d.genericString)))("Nested 1")(new h.Just(new l.Tuple(3,"foo")))();
a(f.interactiveTuple(d.genericInt)(d.genericTuple(d.genericInt)(d.genericTuple(d.genericInt)(d.genericTuple(d.genericInt)(d.genericBool)))))("Nested 2")(new l.Tuple(1,new l.Tuple(2,new l.Tuple(3,new l.Tuple(4,!1)))))();a(f.interactiveArray(d.genericArray(d.genericArray(d.genericArray(d.genericInt)))))("Nested Arrays")([[[[1],[2,3]],[[4]]]])();a(K)("Records")({num:42.3,str:"foo",bool:!1,optional:new h.Just("\ud83d\udd25"),arr:[2,17]})();a(f.interactiveFunction(f.flammableNonNegativeInt)(f.interactiveInt))("NonNegativeInt")(function(a){return a})();
a(f.interactiveFunction(f.flammableSmallInt)(f.interactiveInt))("SmallInt")(function(a){return a})();a(f.interactiveFunction(f.flammableSmallNumber)(f.interactiveNumber))("SmallNumber")(function(a){return a})();a(f.interactiveFunction(f.flammableMultiline)(f.interactiveString))("Multiline")(function(a){return a})();return a(f.interactiveFunction(f.flammableWrapEnum(D)(J))(f.interactiveWrapEnum(u)))("WrapEnum")(c.id(c.categoryFn))()};a.testToEnum=v;a.testFromEnum=B;a.flammableTRegex=I;a.genericFoo=
n;a.interactiveFoo=K;a.genericTestEnum=u;a.showTestEnum=J;a.boundedTestEnum=m;a.enumTestEnum=D})(PS["Test.Main"]=PS["Test.Main"]||{});PS["Test.Main"].main();
